# Generated by Django 3.0.6 on 2020-05-30 00:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasCompany',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this Gas Company should be treated as active. Unselect this instead of deleting Gas Stations.', verbose_name='active')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Gas_Station_Address', to='Addresses.Address')),
            ],
        ),
    ]
