# Generated by Django 3.0.6 on 2020-05-30 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GasCompany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasCompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GasCompany.GasCompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_Admin_GasCompany', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
