# Generated by Django 3.0.6 on 2020-05-30 01:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('GasCompany', '0002_gascompanyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gascompanyuser',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
