# Generated by Django 3.0.6 on 2020-05-27 22:41

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=300)),
                ('neighborhood', models.CharField(max_length=300)),
                ('inner_number', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)])),
                ('outer_number', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)])),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('municipality', models.CharField(max_length=300)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
    ]
