# Generated by Django 3.0.6 on 2020-05-30 02:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gelocation', '0001_initial'),
        ('TankerTruck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=300)),
                ('raw_data', models.CharField(max_length=50)),
                ('geodata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geodata_event', to='Gelocation.Geolocation')),
                ('tanker_truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tanker_trucks_event', to='TankerTruck.TankerTruck')),
            ],
        ),
    ]
