# Generated by Django 3.0.6 on 2020-06-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PricesDiscount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='Price_Description',
            new_name='Discount_Description',
        ),
    ]
