# Generated by Django 3.0.6 on 2020-05-27 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gelocation', '0001_initial'),
        ('ServiceArea', '0001_initial'),
        ('PricesDiscount', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observations', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_client', to='Addresses.Address')),
                ('credit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_client', to='PricesDiscount.Credit')),
                ('geolocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gelocation_client', to='Gelocation.Geolocation')),
                ('service_area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_area_client', to='ServiceArea.ServiceArea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
