# Generated by Django 3.0.6 on 2020-05-27 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
            ],
        ),
    ]
