# Generated by Django 3.0.6 on 2020-05-30 02:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GasCompany', '0003_auto_20200530_0154'),
        ('ServiceArea', '0002_auto_20200527_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankerTruck',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this Tanker Truck should be treated as active. Unselect this instead of deleting Tanker Trucks.', verbose_name='active')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_operators_tanker_truck', to='GasCompany.GasCompanyUser')),
                ('service_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_ares_tanker_truck', to='ServiceArea.ServiceArea')),
            ],
        ),
    ]
