# Generated by Django 3.0.6 on 2020-05-27 22:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PricesDiscount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('discount', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PricesDiscount.Discount')),
                ('price', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PricesDiscount.Price')),
            ],
        ),
    ]
