# Generated by Django 3.0.6 on 2020-05-27 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PricesDiscount', '0001_initial'),
        ('ServiceArea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='discount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_service_area', to='PricesDiscount.Discount'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_service_area', to='PricesDiscount.Price'),
        ),
    ]
