# Generated by Django 3.0.6 on 2020-06-11 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GasCompany', '0003_auto_20200530_0154'),
        ('ServiceArea', '0002_auto_20200527_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='gas_company',
            field=models.ForeignKey(default='2ab524ba-4fc5-43e1-a7a0-15d4a1ff9768', on_delete=django.db.models.deletion.CASCADE, to='GasCompany.GasCompany'),
            preserve_default=False,
        ),
    ]
