# Generated by Django 3.0.6 on 2020-06-11 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GasCompany', '0003_auto_20200530_0154'),
        ('ServiceArea', '0003_servicearea_gas_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='gas_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_company_of_service_area', to='GasCompany.GasCompany'),
        ),
    ]
