# Generated by Django 3.0.6 on 2020-06-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellNumber2',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, unique=True),
        ),
    ]
